name: Reusable workflow
on: workflow_call
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./artifact
      - name: Deploy to Azure Web App (Publish Profile)
        uses: azure/webapps-deploy@v3
        with:
          app-name: demoappactions
          package: ./artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
      - name: Output
        run: echo "Deploying....."
